version: 2.1

parameters:
  image-tag:
    type: string
    default: "0.1.0"

jobs:

  deps:
    docker:
      - image: supraxelgames/cusco-buildimage:<<pipeline.parameters.image-tag>>
    resource_class: small
    steps:
      - checkout:
          name: Checkout Git repository
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  format-check:
    docker:
      - image: supraxelgames/cusco-buildimage:<<pipeline.parameters.image-tag>>
    resource_class: small
    steps:
      - checkout:
          name: Checkout Git repository
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Check formatting
          command: nx affected --configuration=production --target=format:check

  tests:
    docker:
      - image: supraxelgames/cusco-buildimage:<<pipeline.parameters.image-tag>>
    resource_class: medium
    steps:
      - checkout:
          name: Checkout Git repository
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run unit tests
          command: |
            dotnet restore
            nx affected --target=test
  # ### see https://circleci.com/docs/2.0/collect-test-data#dot-net

  nuget:
    docker:
      - image: supraxelgames/cusco-buildimage:<<pipeline.parameters.image-tag>>
    resource_class: medium
    steps:
      - checkout:
          name: Checkout Git repository
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build release configuration
          command: |-
            rm -rf -o nugets
            dotnet restore
            dotnet pack -c Release -p:VersionPrefix=$(node -p "require('./package.json').version").$CUSCO_BUILD_NUM;SourceRevisionId=<<pipeline.git.revision>>;RepositoryUrl=<<pipeline.project.git_url>>;RepositoryType=git;RepositoryBranch=<<pipeline.git.branch>>;IncludeSymbols=true;SymbolPackageFormat=snupkg
            for nuget in nugets/*.nupkg ; do dotnet nuget push $nuget -k $NUGET_KEY --source https://api.nuget.org/v3/index.json ; done

workflows:
  main:
    jobs:
      - deps
      - format-check:
          requires: [ deps ]
      - tests:
          requires: [ deps ]
      - nuget:
          requires:
            - deps
            - format-check
            - tests
