version: 2.1

parameters:
  image-tag:
    type: string
    default: "0.1.0"

setup:


jobs:
  format-check:
    docker:
      - image: supraxelgames/cusco-buildimage:<<pipeline.parameters.image-tag>>
    resource_class: small
    steps:
      - checkout:
          name: Checkout Git repository
      - run:
          name: Install NPM dependencies
          command: npm install
      - run:
          name: Check formatting
          command: nx affected --configuration=production --target=format:check

  tests:
    docker:
      - image: supraxelgames/cusco-buildimage:<<pipeline.parameters.image-tag>>
    resource_class: medium
    steps:
      - checkout:
          name: Checkout Git repository
      - run:
          name: Install NPM dependencies
          command: npm install
      - run:
          name: Run unit tests
          command: nx affected --target=test # --logger "trx"
  # ### see https://circleci.com/docs/2.0/collect-test-data#dot-net
  #      - run:
  #          name: Reformat test results
  #          command: |
  #            dotnet tool install -g trx2junit
  #            export PATH="$PATH:/root/.dotnet/tools"
  #            trx2junit tests/**/TestResults/*.trx

  nuget:
    docker:
      - image: supraxelgames/cusco-buildimage:<<pipeline.parameters.image-tag>>
    resource_class: medium
    steps:
      - checkout:
          name: Checkout Git repository
      - run:
          name: Install NPM dependencies
          command: npm install
      - run:
          name: Build release configuration
          command: |-
            rm -rf -o nugets
            dotnet pack -c Release -p:VersionPrefix=$(node -p "require('./package.json').version").$CUSCO_BUILD_NUM;SourceRevisionId=<<pipeline.git.revision>>;RepositoryUrl=<<pipeline.project.git_url>>;RepositoryType=git;RepositoryBranch=<<pipeline.git.branch>>;IncludeSymbols=true;SymbolPackageFormat=snupkg
            for nuget in nugets/*.nupkg ; do dotnet nuget push $nuget -k $NUGET_KEY --source https://api.nuget.org/v3/index.json ; done

workflows:
  main:
    jobs:
      - format-check
      - tests
      - nuget:
          requires:
            - format-check
            - tests
