version: 2.1

parameters:
  image-tag:
    type: string
    default: "0.1.0"

setup:


jobs:
  #  format-check:
  #    docker:
  #      - image: supraxelgames/cusco-buildimage:<< pipeline.parameters.image-tag >>
  #    steps:
  #      - checkout:
  #          name: Checkout Git repository
  #      - run:
  #          name: Check formatting
  #          command: nx affected --configuration=production --target=format:check

  test:
    docker:
      - image: supraxelgames/cusco-buildimage:<< pipeline.parameters.image-tag >>
    steps:
      - checkout:
          name: Checkout Git repository
      - run:
          name: Install NPM dependencies
          command: npm install
      - run:
          name: Run unit tests
          command: nx affected --target=test

#  build:
#    docker:
#      - image: supraxelgames/cusco-buildimage:<< pipeline.parameters.image-tag >>
#    steps:
#      - checkout:
#          name: Checkout Git repository
#      - run:
#          name: Build release configuration
#          command: nx affected --configuration=production --target=build --all

workflows:
  pull-request:
    jobs:
      - test
