version: 2.1

parameters:
  image-tag:
    type: string
    default: "0.1.0"

jobs:
  test:
    docker:
      - image: supraxelgames/cusco-buildimage:<< pipeline.parameters.image-tag >>
    steps:
      - checkout:
          name: Checkout Git repository
      - run:
          name: Hosts
          command: cat /etc/hosts
      - run:
          name: Resolv.conf
          command: cat /etc/resolv.conf
      - run:
          name: dig api.nuget.org
          command: apt-get install -y dnsutils && dig api.nuget.org
      - run:
          name: curl api.nuget.org
          command: apt-get install -y curl && curl https://api.nuget.org/v3/index.json
      - run:
          name: Install NPM dependencies
          command: npm install
      - run:
          name: Restore .NET dependencies
          command: dotnet restore -f
      - run:
          name: Run unit tests
          command: nx affected --configuration=production --target=test

workflows:
  pull-request:
    jobs:
      - test
